name: Documentation

on:
  push:
    branches:
      - main  # or 'master' or whatever the default branch is

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build and deploy
        run: |
          julia --project=docs docs/make.jl

        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
